package com.seanshubin.kotlin.tryme.domain.jvmclassformat.two.instructionset

enum class OpCodeArgs {
    NONE,
    LOCAL_VARIABLE_INDEX,
    CONSTANT_POOL_INDEX,
    BYTE_VALUE,
    BRANCH_OFFSET,
    BRANCH_OFFSET_WIDE,
    INDEX_CONST,
    CONSTANT_POOL_INDEX_THEN_TWO_ZEROES,
    CONSTANT_POOL_INDEX_THEN_COUNT_THEN_ZERO,
    CONSTANT_POOL_INDEX_SHORT,
    LOOKUP_SWITCH,
    CONSTANT_POOL_INDEX_THEN_DIMENSIONS,
    ARRAY_TYPE,
    SHORT_VALUE,
    TABLE_SWITCH,
    WIDE;
}
